### ISSUE TITLE
Cannot install crossword

### ISSUE THREAD

**Issue by flystar233** [USDA-ARS-GBRU/crossword#1]
> devtools::install_github("USDA-ARS-GBRU/crossword")
Error in read.dcf(path) : 
  Found continuation line starting '    role = c("aut",  ...' at begin of record.

Installation of direct cloning projects also failed

**Comment by w-korani** [comment]
it is an odd issue. Sometimes happening with some operating system for many Github packages when it processes the DESCRIPTION file. Anyway, I did some change in the mentioned file that may fix the issue. Please try again.

**Comment by w-korani** [comment]
Closes #1
